name: vivo_stage3_final_v23
model_type: mimo_pan_Model_075_s4
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: SigalREDSDJPGataset
    dataroot_gt: /opt/data/share/121106010692/B100/redsjpg/train_sharp
    dataroot_lq: /opt/data/share/121106010692/B100/redsjpg/train_blur_jpeg
#    dataroot_gt: ../datasets/REDS/train/train_sharp
#    dataroot_lq: ../datasets/REDS/train/train_blur_jpeg
    dataroot_flow: ~
    meta_info_file: data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    gt_size: 256
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: SigalREDSDJPGataset
    dataroot_gt: /opt/data/share/121106010692/B100/redsjpg/val_reds4_sharp
    dataroot_lq: /opt/data/share/121106010692/B100/redsjpg/val_reds4_blur_jpeg
#    dataroot_gt: ../datasets/REDS/val/val_reds4_sharp
#    dataroot_lq: ../datasets/REDS/val/val_reds4_blur_jpeg
    meta_info_file: data/meta_info/meta_info_REDS4_test_GT.txt
    io_backend:
      type: disk

    patch_size: 256



# network structures
network_g:
  type: DEBLUR_stage3_final_V49
  scale_fact: 0.75




# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000, 200000]
    restart_weights: [1, 0.5]
    eta_min: !!float 1e-7

#  scheduler:
#    type: MultiStepLR
#    milestones: [50000]
#    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
